apiVersion: v1
kind: Service
metadata:
  name: book-api-service
  labels:
    app: book-api
spec:
  selector:
    app: book-api
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30001
    protocol: TCP
    name: http
  type: NodePort